# 로컬 테스트용 파일입니다.
version: "3.8"
services:
  api-service:
    build:
      context: "./"
      dockerfile: Dockerfile
    image: "jp3pe/belf-kr/api-service"
    container_name: "belf-api-service"
    environment:
      - SERVER_PORT=3000
      - SERVER_PORT_OAUTH=3001
      - SERVER_PORT_MOCK=3002
      - SERVER_PORT_TODO=3003
      - SERVER_PORT_STORAGE=3004
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:docker"]
