apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/belf-kr/api-gateway/nestjs
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: api-gateway
