@Host = http://localhost:3000
# @Host = https://api-gateway.qa.belf.xyz
@Router = todo

### 오늘 하루 todo list 조회
GET {{Host}}/{{Router}}/today-todos

### 잔디밭 조회
GET {{Host}}/{{Router}}/glass

### color 정보 전체 조회
GET {{Host}}/{{Router}}/colors
Content-Type: application/json

### course 정보 전체 조회
GET {{Host}}/{{Router}}/courses
Content-Type: application/json

### course 생성
POST {{Host}}/{{Router}}/create-course
Content-Type: application/json

{
    "color": "#FF8484",
    "title": "영어공부하기3",
    "explanation": "토익 ...",
    "tags": [
        {
            "value": "자동차"
        },
        {
            "value": "차차차"
        }
    ]
}

### course 삭제
DELETE {{Host}}/{{Router}}/delete-courses
Content-Type: application/json

{
    "id": 6555
}

### work_todo 추가
POST {{Host}}/{{Router}}/create-work-todo
Content-Type: application/json

{
    "courseId": 65,
    "recurringCycleDate": 1,
    "title": "나만의 할 일3",
    "explanation": "나만의 할 일 설명3",
    "passedDay": 5
}

### work_todo 전체 리스트 가져오기
GET {{Host}}/{{Router}}/work-todos
Content-Type: application/json

### work_todo 삭제
DELETE {{Host}}/{{Router}}/delete-work-todo
Content-Type: application/json

{
    "id": 1,
    "title": "나만의 할 일3",
    "explanation": "설명입니다.",
    "courseId": 3
}