@Host = http://localhost:3000
# @Host = https://api-gateway.qa.belf.xyz
@Router = todo

### Get service name
GET {{Host}}/{{Router}}

### Get ping
GET {{Host}}/{{Router}}/ping

### Get env
GET {{Host}}/{{Router}}/env

### Get version
GET {{Host}}/{{Router}}/version

### color 정보 전체 조회
GET {{Host}}/{{Router}}/colors

### course 정보 전체 조회
GET {{Host}}/{{Router}}/courses

### course 생성
POST {{Host}}/{{Router}}/courses
authorization: 
Content-Type: application/json

{
    "color": "#FF8484",
    "title": "영어공부하기1",
    "explanation": "토익 ...",
    "tags": [
        {
            "value": "자동차"
        },
        {
            "value": "하하하"
        }
    ]
}

### course 삭제
DELETE {{Host}}/{{Router}}/courses/1

### work_todo 추가(필수)
POST {{Host}}/{{Router}}/work-todos
authorization: 
Content-Type: application/json

{
    "courseId": 1,
    "title": "나만의 할 일1",
    "repeatedDaysOfTheWeek": []
}

### work_todo 추가(선택)
POST {{Host}}/{{Router}}/work-todos
authorization: 
Content-Type: application/json

{
    "courseId": 1,
    "title": "나만의 할 일1",
    "repeatedDaysOfTheWeek": [1, 2, 3],
    "activeDate": "2021-11-05T08:50:00.12",
    "recurringCycleDate": 1,
    "explanation": "나만의 할 일 설명1"
}

### work_todo 전체 리스트 가져오기
GET {{Host}}/{{Router}}/work-todos

### work_todo 리스트 가져오기
GET {{Host}}/{{Router}}/work-todos?courseId=1

### work_todo 삭제
DELETE {{Host}}/{{Router}}/work-todos/1

### work_done 추가
POST {{Host}}/{{Router}}/work-dones
authorization: 
Content-Type: application/json

{
    "workTodoId": 1,
    "title": "한 일의 제목1",
    "content": "json 컨텐츠 1"
}

### work_done 전체 리스트 가져오기
GET {{Host}}/{{Router}}/work-dones

### work_done 리스트 가져오기
GET {{Host}}/{{Router}}/work-dones?courseId=1

### work_done 디테일
GET {{Host}}/{{Router}}/work-dones/1