@Host = http://localhost:3000
# @Host = https://api-gateway.qa.belf.xyz
@Router = storage
@FileId = c00c8482-d1e4-443f-ae9a-7c51abab937d

GET {{Host}}/{{Router}}/file/base64/{{FileId}}

POST {{Host}}/{{Router}}/upload