@Host = http://localhost:3000
# @Host = https://api-gateway.qa.belf.xyz
@Router = storage
@FileId = c00c8482-d1e4-443f-ae9a-7c51abab937d

### Get service name
GET {{Host}}/{{Router}}

### Get ping
GET {{Host}}/{{Router}}/ping

### Get env
GET {{Host}}/{{Router}}/env

### Get version
GET {{Host}}/{{Router}}/version

### Base64 형식으로 파일 가져오기
GET {{Host}}/{{Router}}/file/base64/{{FileId}}

### File upload
POST {{Host}}/{{Router}}/upload
authorization: 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ~/Desktop/storage.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### File delete
DELETE {{Host}}/{{Router}}/delete?fileId={{FileId}}
authorization: 

### File 정보 가져오기
GET {{Host}}/{{Router}}/info/{{FileId}}